### ISSUE TITLE
Publish Action fails validation.

### ISSUE THREAD

**Issue by ck3mp3r** [flakestry/flakestry.dev#47]
```
2024-02-18T14:39:03.7743240Z Download action repository 'flakestry/flakestry-publish@main' (SHA:fd80e4c1432592211aa496126a14d8dbfdd5b373)
2024-02-18T14:39:04.3685558Z ##[error]flakestry/flakestry-publish/main/action.yaml (Line: 29, Col: 12): Unexpected symbol: '"false"'. Located at position 27 within expression: inputs.ignoreConflicts || "false"
2024-02-18T14:39:04.3708041Z ##[error]GitHub.DistributedTask.ObjectTemplating.TemplateValidationException: The template is not valid. flakestry/flakestry-publish/main/action.yaml (Line: 29, Col: 12): Unexpected symbol: '"false"'. Located at position 27 within expression: inputs.ignoreConflicts || "false"
   at GitHub.DistributedTask.ObjectTemplating.TemplateValidationErrors.Check()
   at GitHub.Runner.Worker.ActionManifestManager.ConvertRuns(IExecutionContext executionContext, TemplateContext templateContext, TemplateToken inputsToken, String fileRelativePath, MappingToken outputs)
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
2024-02-18T14:39:04.3735643Z ##[error]Failed to load flakestry/flakestry-publish/main/action.yaml
```

**Comment by ck3mp3r** [comment]
Opened in wrong repo, already reported in https://github.com/flakestry/flakestry-publish/issues/3
